spring:
  datasource:
    url: jdbc:mysql://192.168.31.100:3306/mp_db?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: MyDifficultPass4@
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  global-config:
    db-config:
      # id生成策略 auto为数据库自增
      id-type: auto
    #关闭驼峰映射  当然了不推荐关闭
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
#   map-underscore-to-camel-case: false